import { Category, CreditCard, InstallmentPlan, MonthlyBudget, CategoryBudget, RecurringExpense, Transaction } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  // MORADIA
  { id: 'cat-aluguel', name: 'Aluguel', type: 'expense', group: 'MORADIA', isDefault: true, active: true },
  { id: 'cat-fin-casa', name: 'Financiamento Casa', type: 'expense', group: 'MORADIA', isDefault: true, active: true },
  { id: 'cat-condominio', name: 'Condomínio', type: 'expense', group: 'MORADIA', isDefault: true, active: true },
  { id: 'cat-manut-casa', name: 'Manutenção da Casa', type: 'expense', group: 'MORADIA', isDefault: true, active: true },

  // CONTAS DA CASA
  { id: 'cat-agua', name: 'Água', type: 'expense', group: 'CONTAS DA CASA', isDefault: true, active: true },
  { id: 'cat-luz', name: 'Luz', type: 'expense', group: 'CONTAS DA CASA', isDefault: true, active: true },
  { id: 'cat-internet', name: 'Internet', type: 'expense', group: 'CONTAS DA CASA', isDefault: true, active: true },
  { id: 'cat-telefone', name: 'Telefone', type: 'expense', group: 'CONTAS DA CASA', isDefault: true, active: true },
  { id: 'cat-gas', name: 'Gás', type: 'expense', group: 'CONTAS DA CASA', isDefault: true, active: true },

  // TRANSPORTE
  { id: 'cat-fin-carro', name: 'Financiamento Carro', type: 'expense', group: 'TRANSPORTE', isDefault: true, active: true },
  { id: 'cat-combustivel', name: 'Combustível', type: 'expense', group: 'TRANSPORTE', isDefault: true, active: true },
  { id: 'cat-manut-carro', name: 'Manutenção Carro', type: 'expense', group: 'TRANSPORTE', isDefault: true, active: true },
  { id: 'cat-seguro-carro', name: 'Seguro Carro', type: 'expense', group: 'TRANSPORTE', isDefault: true, active: true },
  { id: 'cat-transporte', name: 'Transporte', type: 'expense', group: 'TRANSPORTE', isDefault: true, active: true },

  // ALIMENTAÇÃO
  { id: 'cat-supermercado', name: 'Supermercado', type: 'expense', group: 'ALIMENTAÇÃO', isDefault: true, active: true },
  { id: 'cat-restaurante', name: 'Restaurante', type: 'expense', group: 'ALIMENTAÇÃO', isDefault: true, active: true },
  { id: 'cat-delivery', name: 'Delivery', type: 'expense', group: 'ALIMENTAÇÃO', isDefault: true, active: true },
  { id: 'cat-lanches', name: 'Lanches', type: 'expense', group: 'ALIMENTAÇÃO', isDefault: true, active: true },

  // SAÚDE
  { id: 'cat-farmacia', name: 'Farmácia', type: 'expense', group: 'SAÚDE', isDefault: true, active: true },
  { id: 'cat-medico', name: 'Médico', type: 'expense', group: 'SAÚDE', isDefault: true, active: true },
  { id: 'cat-exames', name: 'Exames', type: 'expense', group: 'SAÚDE', isDefault: true, active: true },
  { id: 'cat-plano-saude', name: 'Plano de Saúde', type: 'expense', group: 'SAÚDE', isDefault: true, active: true },

  // EDUCAÇÃO
  { id: 'cat-escola', name: 'Escola', type: 'expense', group: 'EDUCAÇÃO', isDefault: true, active: true },
  { id: 'cat-cursos', name: 'Cursos', type: 'expense', group: 'EDUCAÇÃO', isDefault: true, active: true },
  { id: 'cat-material', name: 'Material', type: 'expense', group: 'EDUCAÇÃO', isDefault: true, active: true },

  // LAZER
  { id: 'cat-passeios', name: 'Passeios', type: 'expense', group: 'LAZER', isDefault: true, active: true },
  { id: 'cat-entretenimento', name: 'Entretenimento', type: 'expense', group: 'LAZER', isDefault: true, active: true },
  { id: 'cat-viagens', name: 'Viagens', type: 'expense', group: 'LAZER', isDefault: true, active: true },

  // PESSOAL
  { id: 'cat-roupas', name: 'Roupas', type: 'expense', group: 'PESSOAL', isDefault: true, active: true },
  { id: 'cat-beleza', name: 'Beleza', type: 'expense', group: 'PESSOAL', isDefault: true, active: true },
  { id: 'cat-presentes', name: 'Presentes', type: 'expense', group: 'PESSOAL', isDefault: true, active: true },
  { id: 'cat-outros-gastos', name: 'Outros', type: 'expense', group: 'PESSOAL', isDefault: true, active: true },

  // ENTRADAS
  { id: 'cat-salario', name: 'Salário', type: 'income', group: 'ENTRADAS', isDefault: true, active: true },
  { id: 'cat-vale', name: 'Vale', type: 'income', group: 'ENTRADAS', isDefault: true, active: true },
  { id: 'cat-renda-extra', name: 'Renda Extra', type: 'income', group: 'ENTRADAS', isDefault: true, active: true },
  { id: 'cat-reembolso', name: 'Reembolso', type: 'income', group: 'ENTRADAS', isDefault: true, active: true },
  { id: 'cat-outras-entradas', name: 'Outros (Entradas)', type: 'income', group: 'ENTRADAS', isDefault: true, active: true },
];

export const INITIAL_RECURRING_EXPENSES: RecurringExpense[] = [
  {
    id: 'rec-1',
    description: 'Financiamento Casa',
    categoryId: 'cat-fin-casa',
    amount: 1200.0,
    dueDay: 10,
    frequency: 'monthly',
    paymentMethod: 'boleto',
    expenseType: 'fixed',
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'rec-2',
    description: 'Financiamento Carro',
    categoryId: 'cat-fin-carro',
    amount: 850.0,
    dueDay: 15,
    frequency: 'monthly',
    paymentMethod: 'boleto',
    expenseType: 'fixed',
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'rec-3',
    description: 'Água',
    categoryId: 'cat-agua',
    amount: 80.0,
    dueDay: 5,
    frequency: 'monthly',
    paymentMethod: 'pix',
    expenseType: 'fixed',
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'rec-4',
    description: 'Luz',
    categoryId: 'cat-luz',
    amount: 150.0,
    dueDay: 8,
    frequency: 'monthly',
    paymentMethod: 'pix',
    expenseType: 'fixed',
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'rec-5',
    description: 'Internet',
    categoryId: 'cat-internet',
    amount: 100.0,
    dueDay: 20,
    frequency: 'monthly',
    paymentMethod: 'debito',
    expenseType: 'fixed',
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'rec-6',
    description: 'Plano de Saúde',
    categoryId: 'cat-plano-saude',
    amount: 320.0,
    dueDay: 12,
    frequency: 'monthly',
    paymentMethod: 'boleto',
    expenseType: 'fixed',
    active: true,
    createdAt: '2026-01-01',
  },
];

export const INITIAL_CREDIT_CARDS: CreditCard[] = [
  { id: 'card-1', name: 'Nubank Platinum', closingDay: 28, dueDay: 5, limit: 5000 },
  { id: 'card-2', name: 'Itaú Cartão', closingDay: 15, dueDay: 22, limit: 8000 },
];

export const INITIAL_INSTALLMENT_PLANS: InstallmentPlan[] = [
  {
    id: 'inst-1',
    description: 'Smart TV 55"',
    creditCardId: 'card-1',
    categoryId: 'cat-entretenimento',
    purchaseDate: '2026-05-10',
    totalAmount: 2400,
    installments: 12,
    installmentAmount: 200,
    expenseType: 'variable',
    createdAt: '2026-05-10',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // --- AGOSTO 2026 (Exemplo principal do usuário) ---
  {
    id: 'tx-aug-1',
    type: 'income',
    date: '2026-08-01',
    description: 'Salário Mensal',
    categoryId: 'cat-salario',
    amount: 4000.0,
    expenseType: 'fixed',
    paymentMethod: 'transferencia',
    notes: 'Depósito na conta corrente',
    recurrence: 'monthly',
    createdAt: '2026-08-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'tx-aug-2',
    type: 'expense',
    date: '2026-08-10',
    description: 'Financiamento Casa',
    categoryId: 'cat-fin-casa',
    amount: 1200.0,
    expenseType: 'fixed',
    paymentMethod: 'boleto',
    recurrence: 'monthly',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-10',
  },
  {
    id: 'tx-aug-3',
    type: 'expense',
    date: '2026-08-15',
    description: 'Financiamento Carro',
    categoryId: 'cat-fin-carro',
    amount: 850.0,
    expenseType: 'fixed',
    paymentMethod: 'boleto',
    recurrence: 'monthly',
    createdAt: '2026-08-15',
    updatedAt: '2026-08-15',
  },
  {
    id: 'tx-aug-4',
    type: 'expense',
    date: '2026-08-05',
    description: 'Conta de Água',
    categoryId: 'cat-agua',
    amount: 80.0,
    expenseType: 'fixed',
    paymentMethod: 'pix',
    recurrence: 'monthly',
    createdAt: '2026-08-05',
    updatedAt: '2026-08-05',
  },
  {
    id: 'tx-aug-5',
    type: 'expense',
    date: '2026-08-08',
    description: 'Conta de Luz',
    categoryId: 'cat-luz',
    amount: 150.0,
    expenseType: 'fixed',
    paymentMethod: 'pix',
    recurrence: 'monthly',
    createdAt: '2026-08-08',
    updatedAt: '2026-08-08',
  },
  {
    id: 'tx-aug-6',
    type: 'expense',
    date: '2026-08-20',
    description: 'Internet Fibra',
    categoryId: 'cat-internet',
    amount: 100.0,
    expenseType: 'fixed',
    paymentMethod: 'debito',
    recurrence: 'monthly',
    createdAt: '2026-08-20',
    updatedAt: '2026-08-20',
  },
  {
    id: 'tx-aug-7',
    type: 'expense',
    date: '2026-08-06',
    description: 'Compra Supermercado Semanal',
    categoryId: 'cat-supermercado',
    amount: 600.0,
    expenseType: 'variable',
    paymentMethod: 'credito',
    notes: 'Compras de mantimentos para a quinzena',
    recurrence: 'none',
    createdAt: '2026-08-06',
    updatedAt: '2026-08-06',
  },
  {
    id: 'tx-aug-8',
    type: 'expense',
    date: '2026-08-12',
    description: 'Posto de Combustível',
    categoryId: 'cat-combustivel',
    amount: 300.0,
    expenseType: 'variable',
    paymentMethod: 'debito',
    recurrence: 'none',
    createdAt: '2026-08-12',
    updatedAt: '2026-08-12',
  },
  {
    id: 'tx-aug-9',
    type: 'expense',
    date: '2026-08-07',
    description: 'Passeio em Família e Lazer',
    categoryId: 'cat-lazer',
    amount: 200.0,
    expenseType: 'variable',
    paymentMethod: 'pix',
    recurrence: 'none',
    createdAt: '2026-08-07',
    updatedAt: '2026-08-07',
  },

  // --- JULHO 2026 (Para comparação e gráficos) ---
  {
    id: 'tx-jul-1',
    type: 'income',
    date: '2026-07-01',
    description: 'Salário Mensal',
    categoryId: 'cat-salario',
    amount: 4000.0,
    expenseType: 'fixed',
    paymentMethod: 'transferencia',
    recurrence: 'monthly',
    createdAt: '2026-07-01',
    updatedAt: '2026-07-01',
  },
  {
    id: 'tx-jul-2',
    type: 'income',
    date: '2026-07-15',
    description: 'Renda Extra Freelance',
    categoryId: 'cat-renda-extra',
    amount: 500.0,
    expenseType: 'variable',
    paymentMethod: 'pix',
    recurrence: 'none',
    createdAt: '2026-07-15',
    updatedAt: '2026-07-15',
  },
  {
    id: 'tx-jul-3',
    type: 'expense',
    date: '2026-07-10',
    description: 'Financiamento Casa',
    categoryId: 'cat-fin-casa',
    amount: 1200.0,
    expenseType: 'fixed',
    paymentMethod: 'boleto',
    recurrence: 'monthly',
    createdAt: '2026-07-10',
    updatedAt: '2026-07-10',
  },
  {
    id: 'tx-jul-4',
    type: 'expense',
    date: '2026-07-15',
    description: 'Financiamento Carro',
    categoryId: 'cat-fin-carro',
    amount: 850.0,
    expenseType: 'fixed',
    paymentMethod: 'boleto',
    recurrence: 'monthly',
    createdAt: '2026-07-15',
    updatedAt: '2026-07-15',
  },
  {
    id: 'tx-jul-5',
    type: 'expense',
    date: '2026-07-08',
    description: 'Conta de Luz',
    categoryId: 'cat-luz',
    amount: 130.0,
    expenseType: 'fixed',
    paymentMethod: 'pix',
    recurrence: 'monthly',
    createdAt: '2026-07-08',
    updatedAt: '2026-07-08',
  },
  {
    id: 'tx-jul-6',
    type: 'expense',
    date: '2026-07-05',
    description: 'Supermercado Mês Anterior',
    categoryId: 'cat-supermercado',
    amount: 700.0,
    expenseType: 'variable',
    paymentMethod: 'credito',
    recurrence: 'none',
    createdAt: '2026-07-05',
    updatedAt: '2026-07-05',
  },

  // --- JUNHO 2026 (Para gráficos) ---
  {
    id: 'tx-jun-1',
    type: 'income',
    date: '2026-06-01',
    description: 'Salário Mensal',
    categoryId: 'cat-salario',
    amount: 4000.0,
    expenseType: 'fixed',
    paymentMethod: 'transferencia',
    recurrence: 'monthly',
    createdAt: '2026-06-01',
    updatedAt: '2026-06-01',
  },
  {
    id: 'tx-jun-2',
    type: 'expense',
    date: '2026-06-10',
    description: 'Financiamento Casa',
    categoryId: 'cat-fin-casa',
    amount: 1200.0,
    expenseType: 'fixed',
    paymentMethod: 'boleto',
    recurrence: 'monthly',
    createdAt: '2026-06-10',
    updatedAt: '2026-06-10',
  },
  {
    id: 'tx-jun-3',
    type: 'expense',
    date: '2026-06-15',
    description: 'Financiamento Carro',
    categoryId: 'cat-fin-carro',
    amount: 850.0,
    expenseType: 'fixed',
    paymentMethod: 'boleto',
    recurrence: 'monthly',
    createdAt: '2026-06-15',
    updatedAt: '2026-06-15',
  },
  {
    id: 'tx-jun-4',
    type: 'expense',
    date: '2026-06-12',
    description: 'Supermercado Junho',
    categoryId: 'cat-supermercado',
    amount: 650.0,
    expenseType: 'variable',
    paymentMethod: 'credito',
    recurrence: 'none',
    createdAt: '2026-06-12',
    updatedAt: '2026-06-12',
  },
];

export const INITIAL_MONTHLY_BUDGETS: MonthlyBudget[] = [
  { id: 'mb-aug-2026', monthYear: '2026-08', overallAmount: 4000.0 },
  { id: 'mb-jul-2026', monthYear: '2026-07', overallAmount: 4000.0 },
];

export const INITIAL_CATEGORY_BUDGETS: CategoryBudget[] = [
  { id: 'cb-aug-super', monthYear: '2026-08', categoryId: 'cat-supermercado', amount: 800.0 },
  { id: 'cb-aug-lazer', monthYear: '2026-08', categoryId: 'cat-lazer', amount: 300.0 },
  { id: 'cb-aug-combustivel', monthYear: '2026-08', categoryId: 'cat-combustivel', amount: 400.0 },
];
